import type { LanguageCode } from "../_i18n/translations";

export const trackerName = "Trackora";

export type CabinetSection =
  | "home"
  | "employees"
  | "clients"
  | "finance"
  | "statistics"
  | "weekly-report"
  | "monthly-report"
  | "settings";

export const cabinetCopy = {
  uk: {
    title: "Кабінет керування",
    description:
      "Обери розділ, з яким хочеш працювати зараз. Працівники, звіти й налаштування тепер розділені по окремих плитках.",
    backToMenu: "Назад до меню",
    menu: {
      home: "Головна",
      employees: "Працівники",
      clients: "Контрагенти",
      statistics: "Статистика",
      weeklyReport: "Звіт за тиждень",
      monthlyReport: "Звіт за місяць",
      settings: "Налаштування",
      signOut: "Вихід з кабінету",
      finance: "Доходи та витрати",
    },
    hints: {
      home: "Огляд кабінету",
      employees: "Список і картки команди",
      clients: "Замовлення й клієнти",
      statistics: "Порівняння продуктивності",
      weeklyReport: "Години та виплати за тиждень",
      monthlyReport: "Зведення за поточний місяць",
      settings: "Мова та параметри кабінету",
      signOut: "Завершити сесію",
      finance: "Фінансовий облік по місяцях",
    },
    weeklyTitle: "Звіт за тиждень",
    monthlyTitle: "Звіт за місяць",
    statisticsTitle: "Статистика команди",
    statisticsDescription:
      "Порівняй продуктивність працівників за загальними годинами, робочими днями, вихідними й лікарняними.",
    statisticsSummary: "Огляд по працівниках",
    statisticsMetricHours: "Загальні години",
    statisticsMetricWorkedDays: "Робочі дні",
    statisticsMetricDaysOff: "Вихідні",
    statisticsMetricSickLeave: "Лікарняні",
    statisticsMetricAverage: "Середні години/день",
    statisticsStatusTopPerformer: "Топ-активний",
    statisticsStatusNeedsAttention: "Потребує уваги",
    statisticsStatusSteady: "Стабільний",
    statisticsSidebarTopPerformer: "Топ-активний",
    statisticsSidebarNeedsAttention: "Потребує уваги",
    statisticsSidebarNoData: "Немає даних",
    settingsTitle: "Налаштування",
    clientsTitle: "Контрагенти та замовлення",
    // new section
    financeTitle: "Доходи та витрати",
    financeDescription:
      "Веди облік доходів і витрат компанії. Дані групуються по місяцях.",
    financeAddEntry: "Додати запис",
    financeType: "Тип",
    financeTypeIncome: "Дохід",
    financeTypeExpense: "Витрата",
    financeCategory: "Категорія",
    financeCategorySalary: "Зарплата",
    financeCategoryRent: "Оренда",
    financeCategoryMaterials: "Матеріали",
    financeCategoryUtilities: "Комунальні",
    financeCategoryTransport: "Транспорт",
    financeCategoryTaxes: "Податки",
    financeCategoryOther: "Інше",
    financeAmount: "Сума",
    financeDescriptionLabel: "Опис",
    financeDescriptionPlaceholder: "Короткий опис запису...",
    financeEntryDate: "Дата",
    financeSave: "Зберегти запис",
    financeDelete: "Видалити",
    financeEmptyTitle: "Поки немає записів",
    financeEmptyDescription:
      "Додай перший запис про дохід або витрату цього місяця.",
    financeIncomeTotal: "Доходи за місяць",
    financeExpenseTotal: "Витрати за місяць",
    financeBalance: "Баланс",
    financePreviousMonth: "Попередній місяць",
    financeNextMonth: "Наступний місяць",
    financeCurrentMonth: "Поточний місяць",
    financeListTitle: "Записи за місяць",
    ///////////////////////////////
    clientsDescription:
      "Додавай замовлення клієнтів, зазначай дату, ім'я та прізвище, додаткові примітки й відповідального працівника.",
    clientsEmptyTitle: "Поки немає замовлень",
    clientsEmptyDescription: "Додай перше замовлення через форму справа.",
    orderDate: "Дата замовлення",
    firstName: "Ім'я",
    lastName: "Прізвище",
    street: "Вулиця",
    additionalNotes: "Додаткові примітки",
    assignedEmployee: "Виконавець",
    selectEmployee: "Оберіть працівника",
    completed: "Виконано",
    transferred: "Перенесено",
    markCompleted: "Виконано",
    markTransferred: "Перенести",
    deleteOrder: "Видалити",
    saveClientOrder: "Додати замовлення",
    clientListTitle: "Список замовлень",
    clientListSubtitle: "Останні замовлення відображаються тут.",
    clientName: "Клієнт",
    noNotes: "Без додаткових приміток",
    listViewLabel: "Список",
    tableViewLabel: "Таблиця",
    pendingStatus: "В очікуванні",
    notTransferredStatus: "Не перенесено",
    weeklyDescription:
      "Коротке зведення по відкритому тижню. Детальні звіти можна розширити пізніше окремими таблицями.",
    monthlyDescription:
      "Поточний місячний підсумок по всіх працівниках з урахуванням закритих тижнів.",
    settingsDescription:
      "Базові налаштування кабінету. Зараз тут доступний вибір мови інтерфейсу.",
    employeesCount: "Працівників",
    activeWeekHours: "Годин за тиждень",
    pendingWeekPay: "До виплати за тиждень",
    activeMonthHours: "Годин за місяць",
    pendingMonthPay: "До виплати за місяць",
    downloadMonthlyPdf: "Завантажити PDF",
    /// Statistics
    statisticsSearchPlaceholder: "Пошук за іменем або посадою...",
    statisticsSortLabel: "Сортувати за",
    statisticsSortName: "Ім'я",
    statisticsSortHours: "Загальні години",
    statisticsSortWorkedDays: "Робочі дні",
    statisticsSortDaysOff: "Вихідні",
    statisticsSortSickLeave: "Лікарняні",
    statisticsFilterLabel: "Фільтр",
    statisticsFilterAll: "Усі",
    statisticsFilterTopPerformer: "Топ-активні",
    statisticsFilterNeedsAttention: "Потребують уваги",
    statisticsFilterSteady: "Стабільні",
    statisticsNoResultsTitle: "Нічого не знайдено",
    statisticsNoResultsDescription:
      "Спробуй змінити пошуковий запит або фільтр.",
  },
  en: {
    title: "Workspace menu",
    description:
      "Choose the section you want to work with now. Employees, reports, and settings are split into separate tiles.",
    backToMenu: "Back to menu",
    menu: {
      home: "Home",
      employees: "Employees",
      clients: "Clients",
      statistics: "Statistics",
      weeklyReport: "Weekly report",
      monthlyReport: "Monthly report",
      settings: "Settings",
      signOut: "Sign out",
      finance: "Income & Expenses",
    },
    hints: {
      home: "Workspace overview",
      employees: "Team list and employee cards",
      clients: "Orders and client records",
      statistics: "Compare team productivity",
      weeklyReport: "Weekly hours and payouts",
      monthlyReport: "Current month summary",
      settings: "Language and workspace options",
      signOut: "End the session",
      finance: "Monthly financial tracking",
    },
    weeklyTitle: "Weekly report",
    monthlyTitle: "Monthly report",
    statisticsTitle: "Team statistics",
    statisticsDescription:
      "Compare employee performance by total hours, working days, days off, and sick leave.",
    statisticsSummary: "Performance snapshot",
    statisticsMetricHours: "Total hours",
    statisticsMetricWorkedDays: "Working days",
    statisticsMetricDaysOff: "Days off",
    statisticsMetricSickLeave: "Sick leave",
    statisticsMetricAverage: "Average hours/day",
    statisticsStatusTopPerformer: "Top performer",
    statisticsStatusNeedsAttention: "Needs attention",
    statisticsStatusSteady: "Steady",
    statisticsSidebarTopPerformer: "Top performer",
    statisticsSidebarNeedsAttention: "Needs attention",
    statisticsSidebarNoData: "No data yet",
    settingsTitle: "Settings",
    clientsTitle: "Clients and orders",
    /// new section
    financeTitle: "Income & Expenses",
    financeDescription:
      "Track company income and expenses. Data is grouped by month.",
    financeAddEntry: "Add entry",
    financeType: "Type",
    financeTypeIncome: "Income",
    financeTypeExpense: "Expense",
    financeCategory: "Category",
    financeCategorySalary: "Salary",
    financeCategoryRent: "Rent",
    financeCategoryMaterials: "Materials",
    financeCategoryUtilities: "Utilities",
    financeCategoryTransport: "Transport",
    financeCategoryTaxes: "Taxes",
    financeCategoryOther: "Other",
    financeAmount: "Amount",
    financeDescriptionLabel: "Description",
    financeDescriptionPlaceholder: "Short description of the entry...",
    financeEntryDate: "Date",
    financeSave: "Save entry",
    financeDelete: "Delete",
    financeEmptyTitle: "No entries yet",
    financeEmptyDescription:
      "Add your first income or expense entry for this month.",
    financeIncomeTotal: "Income this month",
    financeExpenseTotal: "Expenses this month",
    financeBalance: "Balance",
    financePreviousMonth: "Previous month",
    financeNextMonth: "Next month",
    financeCurrentMonth: "Current month",
    financeListTitle: "Monthly entries",
    ///
    clientsDescription:
      "Add client orders, note the order date, full name, any extra details, and the staff member who is assigned.",
    clientsEmptyTitle: "No orders yet",
    clientsEmptyDescription: "Add your first order from the form on the right.",
    orderDate: "Order date",
    firstName: "First name",
    lastName: "Last name",
    street: "Street",
    additionalNotes: "Additional notes",
    assignedEmployee: "Assigned employee",
    selectEmployee: "Select employee",
    completed: "Completed",
    transferred: "Transferred",
    markCompleted: "Done",
    markTransferred: "Transfer",
    deleteOrder: "Delete",
    saveClientOrder: "Add order",
    clientListTitle: "Orders list",
    clientListSubtitle: "Recent orders will appear here.",
    clientName: "Client",
    noNotes: "No additional notes",
    listViewLabel: "List",
    tableViewLabel: "Table",
    pendingStatus: "Pending",
    notTransferredStatus: "Not transferred",
    weeklyDescription:
      "A quick summary of the open week. Detailed report tables can be expanded later.",
    monthlyDescription:
      "Current monthly totals across all employees, including closed weeks.",
    settingsDescription:
      "Basic workspace settings. For now, language selection is available here.",
    employeesCount: "Employees",
    activeWeekHours: "Hours this week",
    pendingWeekPay: "Pending this week",
    activeMonthHours: "Hours this month",
    pendingMonthPay: "Pending this month",
    downloadMonthlyPdf: "Download PDF",
    // Statistics
    statisticsSearchPlaceholder: "Search by name or role...",
    statisticsSortLabel: "Sort by",
    statisticsSortName: "Name",
    statisticsSortHours: "Total hours",
    statisticsSortWorkedDays: "Working days",
    statisticsSortDaysOff: "Days off",
    statisticsSortSickLeave: "Sick leave",
    statisticsFilterLabel: "Filter",
    statisticsFilterAll: "All",
    statisticsFilterTopPerformer: "Top performers",
    statisticsFilterNeedsAttention: "Needs attention",
    statisticsFilterSteady: "Steady",
    statisticsNoResultsTitle: "No results found",
    statisticsNoResultsDescription: "Try adjusting the search or filter.",
  },
  de: {
    title: "Arbeitsbereich-Menü",
    description:
      "Wähle den Bereich, mit dem du jetzt arbeiten möchtest. Mitarbeiter, Berichte und Einstellungen sind in separate Kacheln aufgeteilt.",
    backToMenu: "Zurück zum Menü",
    menu: {
      home: "Start",
      employees: "Mitarbeiter",
      clients: "Kunden",
      statistics: "Statistik",
      weeklyReport: "Wochenbericht",
      monthlyReport: "Monatsbericht",
      settings: "Einstellungen",
      signOut: "Abmelden",
      finance: "Einnahmen & Ausgaben",
    },
    hints: {
      home: "Übersicht des Arbeitsbereichs",
      employees: "Teamliste und Mitarbeiterkarten",
      clients: "Bestellungen und Kunden",
      statistics: "Produktivität vergleichen",
      weeklyReport: "Wochenstunden und Auszahlungen",
      monthlyReport: "Übersicht des aktuellen Monats",
      settings: "Sprache und Optionen",
      signOut: "Sitzung beenden",
      finance: "Monatliche Finanzübersicht",
    },
    weeklyTitle: "Wochenbericht",
    monthlyTitle: "Monatsbericht",
    statisticsTitle: "Team-Statistik",
    statisticsDescription:
      "Vergleiche die Leistung der Mitarbeiter nach Gesamtstunden, Arbeitstagen, freien Tagen und Krankheitsausfällen.",
    statisticsSummary: "Leistungsüberblick",
    statisticsMetricHours: "Gesamtstunden",
    statisticsMetricWorkedDays: "Arbeitstage",
    statisticsMetricDaysOff: "Freie Tage",
    statisticsMetricSickLeave: "Krankheitstage",
    statisticsMetricAverage: "Durchschnittliche Stunden/Tag",
    statisticsStatusTopPerformer: "Top-Leistung",
    statisticsStatusNeedsAttention: "Braucht Aufmerksamkeit",
    statisticsStatusSteady: "Stabil",
    statisticsSidebarTopPerformer: "Top-Leistung",
    statisticsSidebarNeedsAttention: "Braucht Aufmerksamkeit",
    statisticsSidebarNoData: "Noch keine Daten",
    settingsTitle: "Einstellungen",
    clientsTitle: "Kunden und Aufträge",
    // new section
    financeTitle: "Einnahmen & Ausgaben",
    financeDescription:
      "Verfolge Einnahmen und Ausgaben des Unternehmens. Daten werden nach Monaten gruppiert.",
    financeAddEntry: "Eintrag hinzufügen",
    financeType: "Typ",
    financeTypeIncome: "Einnahme",
    financeTypeExpense: "Ausgabe",
    financeCategory: "Kategorie",
    financeCategorySalary: "Gehalt",
    financeCategoryRent: "Miete",
    financeCategoryMaterials: "Materialien",
    financeCategoryUtilities: "Nebenkosten",
    financeCategoryTransport: "Transport",
    financeCategoryTaxes: "Steuern",
    financeCategoryOther: "Sonstiges",
    financeAmount: "Betrag",
    financeDescriptionLabel: "Beschreibung",
    financeDescriptionPlaceholder: "Kurze Beschreibung des Eintrags...",
    financeEntryDate: "Datum",
    financeSave: "Eintrag speichern",
    financeDelete: "Löschen",
    financeEmptyTitle: "Noch keine Einträge",
    financeEmptyDescription:
      "Füge deinen ersten Einnahmen- oder Ausgabeneintrag für diesen Monat hinzu.",
    financeIncomeTotal: "Einnahmen diesen Monat",
    financeExpenseTotal: "Ausgaben diesen Monat",
    financeBalance: "Saldo",
    financePreviousMonth: "Vorheriger Monat",
    financeNextMonth: "Nächster Monat",
    financeCurrentMonth: "Aktueller Monat",
    financeListTitle: "Monatliche Einträge",
    /////
    clientsDescription:
      "Füge Kundenaufträge hinzu, trage Datum, Vor- und Nachname, zusätzliche Hinweise und den zuständigen Mitarbeiter ein.",
    clientsEmptyTitle: "Noch keine Aufträge",
    clientsEmptyDescription:
      "Füge deinen ersten Auftrag über das Formular rechts hinzu.",
    orderDate: "Auftragsdatum",
    firstName: "Vorname",
    lastName: "Nachname",
    street: "Straße",
    additionalNotes: "Zusätzliche Hinweise",
    assignedEmployee: "Zuständiger Mitarbeiter",
    selectEmployee: "Mitarbeiter auswählen",
    completed: "Erledigt",
    transferred: "Übertragen",
    markCompleted: "Erledigt",
    markTransferred: "Übertragen",
    deleteOrder: "Löschen",
    saveClientOrder: "Auftrag hinzufügen",
    clientListTitle: "Auftragsliste",
    clientListSubtitle: "Neueste Aufträge werden hier angezeigt.",
    clientName: "Kunde",
    noNotes: "Keine zusätzlichen Hinweise",
    listViewLabel: "Liste",
    tableViewLabel: "Tabelle",
    pendingStatus: "Ausstehend",
    notTransferredStatus: "Nicht übertragen",
    weeklyDescription:
      "Eine kurze Übersicht über die offene Woche. Detaillierte Berichtstabellen können später erweitert werden.",
    monthlyDescription:
      "Aktuelle Monatssummen für alle Mitarbeiter, einschließlich geschlossener Wochen.",
    settingsDescription:
      "Grundeinstellungen des Arbeitsbereichs. Hier kannst du Sprache, Logo und Passwort verwalten.",
    employeesCount: "Mitarbeiter",
    activeWeekHours: "Stunden diese Woche",
    pendingWeekPay: "Ausstehend diese Woche",
    activeMonthHours: "Stunden diesen Monat",
    pendingMonthPay: "Ausstehend diesen Monat",
    downloadMonthlyPdf: "PDF herunterladen",
    // Statistics
    statisticsSearchPlaceholder: "Nach Name oder Rolle suchen...",
    statisticsSortLabel: "Sortieren nach",
    statisticsSortName: "Name",
    statisticsSortHours: "Gesamtstunden",
    statisticsSortWorkedDays: "Arbeitstage",
    statisticsSortDaysOff: "Freie Tage",
    statisticsSortSickLeave: "Krankheitstage",
    statisticsFilterLabel: "Filter",
    statisticsFilterAll: "Alle",
    statisticsFilterTopPerformer: "Top-Leistung",
    statisticsFilterNeedsAttention: "Braucht Aufmerksamkeit",
    statisticsFilterSteady: "Stabil",
    statisticsNoResultsTitle: "Keine Ergebnisse",
    statisticsNoResultsDescription:
      "Versuche die Suche oder den Filter anzupassen.",
  },
  pl: {
    title: "Menu panelu",
    description:
      "Wybierz sekcję, z którą chcesz teraz pracować. Pracownicy, raporty i ustawienia są rozdzielone na osobne kafelki.",
    backToMenu: "Wróć do menu",
    menu: {
      home: "Główna",
      employees: "Pracownicy",
      clients: "Kontrahenci",
      statistics: "Statystyka",
      weeklyReport: "Raport tygodniowy",
      monthlyReport: "Raport miesięczny",
      settings: "Ustawienia",
      signOut: "Wyjście z panelu",
      finance: "Przychody i wydatki",
    },
    hints: {
      home: "Przegląd panelu",
      employees: "Lista i karty zespołu",
      clients: "Zamówienia i klienci",
      statistics: "Porównaj produktywność zespołu",
      weeklyReport: "Godziny i wypłaty za tydzień",
      monthlyReport: "Podsumowanie bieżącego miesiąca",
      settings: "Język i opcje panelu",
      signOut: "Zakończ sesję",
      finance: "Miesięczna ewidencja finansowa",
    },
    weeklyTitle: "Raport tygodniowy",
    monthlyTitle: "Raport miesięczny",
    statisticsTitle: "Statystyka zespołu",
    statisticsDescription:
      "Porównaj produktywność pracowników według łącznych godzin, dni roboczych, dni wolnych i urlopów zdrowotnych.",
    statisticsSummary: "Przegląd wydajności",
    statisticsMetricHours: "Łączne godziny",
    statisticsMetricWorkedDays: "Dni robocze",
    statisticsMetricDaysOff: "Dni wolne",
    statisticsMetricSickLeave: "Nieobecności zdrowotne",
    statisticsMetricAverage: "Średnio godzin/dzień",
    statisticsStatusTopPerformer: "Top wykonawca",
    statisticsStatusNeedsAttention: "Wymaga uwagi",
    statisticsStatusSteady: "Stabilny",
    statisticsSidebarTopPerformer: "Top wykonawca",
    statisticsSidebarNeedsAttention: "Wymaga uwagi",
    statisticsSidebarNoData: "Brak danych",
    settingsTitle: "Ustawienia",
    clientsTitle: "Kontrahenci i zamówienia",
    /// new section
    financeTitle: "Przychody i wydatki",
    financeDescription:
      "Śledź przychody i wydatki firmy. Dane są grupowane według miesięcy.",
    financeAddEntry: "Dodaj wpis",
    financeType: "Typ",
    financeTypeIncome: "Przychód",
    financeTypeExpense: "Wydatek",
    financeCategory: "Kategoria",
    financeCategorySalary: "Wynagrodzenie",
    financeCategoryRent: "Czynsz",
    financeCategoryMaterials: "Materiały",
    financeCategoryUtilities: "Media",
    financeCategoryTransport: "Transport",
    financeCategoryTaxes: "Podatki",
    financeCategoryOther: "Inne",
    financeAmount: "Kwota",
    financeDescriptionLabel: "Opis",
    financeDescriptionPlaceholder: "Krótki opis wpisu...",
    financeEntryDate: "Data",
    financeSave: "Zapisz wpis",
    financeDelete: "Usuń",
    financeEmptyTitle: "Brak wpisów",
    financeEmptyDescription:
      "Dodaj pierwszy wpis przychodu lub wydatku za ten miesiąc.",
    financeIncomeTotal: "Przychody w tym miesiącu",
    financeExpenseTotal: "Wydatki w tym miesiącu",
    financeBalance: "Bilans",
    financePreviousMonth: "Poprzedni miesiąc",
    financeNextMonth: "Następny miesiąc",
    financeCurrentMonth: "Bieżący miesiąc",
    financeListTitle: "Wpisy miesięczne",
    ////
    clientsDescription:
      "Dodawaj zamówienia klientów, podawaj datę, imię i nazwisko, dodatkowe uwagi oraz pracownika odpowiedzialnego.",
    clientsEmptyTitle: "Brak zamówień",
    clientsEmptyDescription:
      "Dodaj pierwsze zamówienie z formularza po prawej stronie.",
    orderDate: "Data zamówienia",
    firstName: "Imię",
    lastName: "Nazwisko",
    street: "Ulica",
    additionalNotes: "Dodatkowe uwagi",
    assignedEmployee: "Wykonawca",
    selectEmployee: "Wybierz pracownika",
    completed: "Wykonane",
    transferred: "Przeniesione",
    markCompleted: "Wykonano",
    markTransferred: "Przenieś",
    deleteOrder: "Usuń",
    saveClientOrder: "Dodaj zamówienie",
    clientListTitle: "Lista zamówień",
    clientListSubtitle: "Najnowsze zamówienia będą widoczne tutaj.",
    clientName: "Klient",
    noNotes: "Brak dodatkowych uwag",
    listViewLabel: "Lista",
    tableViewLabel: "Tabela",
    pendingStatus: "Oczekujące",
    notTransferredStatus: "Nieprzeniesione",
    weeklyDescription:
      "Krótkie podsumowanie otwartego tygodnia. Szczegółowe tabele raportów można rozbudować później.",
    monthlyDescription:
      "Bieżące miesięczne podsumowanie wszystkich pracowników z uwzględnieniem zamkniętych tygodni.",
    settingsDescription:
      "Podstawowe ustawienia panelu. Na razie dostępny jest wybór języka interfejsu.",
    employeesCount: "Pracowników",
    activeWeekHours: "Godzin w tygodniu",
    pendingWeekPay: "Do wypłaty za tydzień",
    activeMonthHours: "Godzin w miesiącu",
    pendingMonthPay: "Do wypłaty za miesiąc",
    downloadMonthlyPdf: "Pobierz PDF",
    // Statistics
    statisticsSearchPlaceholder: "Szukaj po imieniu lub stanowisku...",
    statisticsSortLabel: "Sortuj według",
    statisticsSortName: "Imię",
    statisticsSortHours: "Łączne godziny",
    statisticsSortWorkedDays: "Dni robocze",
    statisticsSortDaysOff: "Dni wolne",
    statisticsSortSickLeave: "Nieobecności zdrowotne",
    statisticsFilterLabel: "Filtr",
    statisticsFilterAll: "Wszyscy",
    statisticsFilterTopPerformer: "Top wykonawcy",
    statisticsFilterNeedsAttention: "Wymagają uwagi",
    statisticsFilterSteady: "Stabilni",
    statisticsNoResultsTitle: "Brak wyników",
    statisticsNoResultsDescription: "Spróbuj zmienić wyszukiwanie lub filtr.",
  },
} as const;

export type CabinetCopy = (typeof cabinetCopy)[LanguageCode];
