import type { LanguageCode } from "../_i18n/translations";

export const trackerName = "Trackora";

export type CabinetSection =
  | "home"
  | "employees"
  | "clients"
  | "weekly-report"
  | "monthly-report"
  | "settings";

export const cabinetCopy = {
  uk: {
    title: "Кабінет керування",
    description:
      "Обери розділ, з яким хочеш працювати зараз. Працівники, звіти й налаштування тепер розділені по окремих плитках.",
    backToMenu: "Назад до меню",
    menu: {
      home: "Головна",
      employees: "Працівники",
      clients: "Контрагенти",
      weeklyReport: "Звіт за тиждень",
      monthlyReport: "Звіт за місяць",
      settings: "Налаштування",
      signOut: "Вихід з кабінету",
    },
    hints: {
      home: "Огляд кабінету",
      employees: "Список і картки команди",
      clients: "Замовлення й клієнти",
      weeklyReport: "Години та виплати за тиждень",
      monthlyReport: "Зведення за поточний місяць",
      settings: "Мова та параметри кабінету",
      signOut: "Завершити сесію",
    },
    weeklyTitle: "Звіт за тиждень",
    monthlyTitle: "Звіт за місяць",
    settingsTitle: "Налаштування",
    clientsTitle: "Контрагенти та замовлення",
    clientsDescription:
      "Додавай замовлення клієнтів, зазначай дату, ім'я та прізвище, додаткові примітки й відповідального працівника.",
    clientsEmptyTitle: "Поки немає замовлень",
    clientsEmptyDescription: "Додай перше замовлення через форму справа.",
    orderDate: "Дата замовлення",
    firstName: "Ім'я",
    lastName: "Прізвище",
    street: "Вулиця",
    additionalNotes: "Додаткові примітки",
    assignedEmployee: "Виконавець",
    selectEmployee: "Оберіть працівника",
    completed: "Виконано",
    transferred: "Перенесено",
    markCompleted: "Виконано",
    markTransferred: "Перенести",
    deleteOrder: "Видалити",
    saveClientOrder: "Додати замовлення",
    clientListTitle: "Список замовлень",
    clientListSubtitle: "Останні замовлення відображаються тут.",
    clientName: "Клієнт",
    noNotes: "Без додаткових приміток",
    weeklyDescription:
      "Коротке зведення по відкритому тижню. Детальні звіти можна розширити пізніше окремими таблицями.",
    monthlyDescription:
      "Поточний місячний підсумок по всіх працівниках з урахуванням закритих тижнів.",
    settingsDescription:
      "Базові налаштування кабінету. Зараз тут доступний вибір мови інтерфейсу.",
    employeesCount: "Працівників",
    activeWeekHours: "Годин за тиждень",
    pendingWeekPay: "До виплати за тиждень",
    activeMonthHours: "Годин за місяць",
    pendingMonthPay: "До виплати за місяць",
    downloadMonthlyPdf: "Завантажити PDF",
  },
  en: {
    title: "Workspace menu",
    description:
      "Choose the section you want to work with now. Employees, reports, and settings are split into separate tiles.",
    backToMenu: "Back to menu",
    menu: {
      home: "Home",
      employees: "Employees",
      clients: "Clients",
      weeklyReport: "Weekly report",
      monthlyReport: "Monthly report",
      settings: "Settings",
      signOut: "Sign out",
    },
    hints: {
      home: "Workspace overview",
      employees: "Team list and employee cards",
      clients: "Orders and client records",
      weeklyReport: "Weekly hours and payouts",
      monthlyReport: "Current month summary",
      settings: "Language and workspace options",
      signOut: "End the session",
    },
    weeklyTitle: "Weekly report",
    monthlyTitle: "Monthly report",
    settingsTitle: "Settings",
    clientsTitle: "Clients and orders",
    clientsDescription:
      "Add client orders, note the order date, full name, any extra details, and the staff member who is assigned.",
    clientsEmptyTitle: "No orders yet",
    clientsEmptyDescription: "Add your first order from the form on the right.",
    orderDate: "Order date",
    firstName: "First name",
    lastName: "Last name",
    street: "Street",
    additionalNotes: "Additional notes",
    assignedEmployee: "Assigned employee",
    selectEmployee: "Select employee",
    completed: "Completed",
    transferred: "Transferred",
    markCompleted: "Done",
    markTransferred: "Transfer",
    deleteOrder: "Delete",
    saveClientOrder: "Add order",
    clientListTitle: "Orders list",
    clientListSubtitle: "Recent orders will appear here.",
    clientName: "Client",
    noNotes: "No additional notes",
    weeklyDescription:
      "A quick summary of the open week. Detailed report tables can be expanded later.",
    monthlyDescription:
      "Current monthly totals across all employees, including closed weeks.",
    settingsDescription:
      "Basic workspace settings. For now, language selection is available here.",
    employeesCount: "Employees",
    activeWeekHours: "Hours this week",
    pendingWeekPay: "Pending this week",
    activeMonthHours: "Hours this month",
    pendingMonthPay: "Pending this month",
    downloadMonthlyPdf: "Download PDF",
  },
  de: {
    title: "Arbeitsbereich-Menü",
    description:
      "Wähle den Bereich, mit dem du jetzt arbeiten möchtest. Mitarbeiter, Berichte und Einstellungen sind in separate Kacheln aufgeteilt.",
    backToMenu: "Zurück zum Menü",
    menu: {
      home: "Start",
      employees: "Mitarbeiter",
      clients: "Kunden",
      weeklyReport: "Wochenbericht",
      monthlyReport: "Monatsbericht",
      settings: "Einstellungen",
      signOut: "Abmelden",
    },
    hints: {
      home: "Übersicht des Arbeitsbereichs",
      employees: "Teamliste und Mitarbeiterkarten",
      clients: "Bestellungen und Kunden",
      weeklyReport: "Wochenstunden und Auszahlungen",
      monthlyReport: "Übersicht des aktuellen Monats",
      settings: "Sprache und Optionen",
      signOut: "Sitzung beenden",
    },
    weeklyTitle: "Wochenbericht",
    monthlyTitle: "Monatsbericht",
    settingsTitle: "Einstellungen",
    clientsTitle: "Kunden und Aufträge",
    clientsDescription:
      "Füge Kundenaufträge hinzu, trage Datum, Vor- und Nachname, zusätzliche Hinweise und den zuständigen Mitarbeiter ein.",
    clientsEmptyTitle: "Noch keine Aufträge",
    clientsEmptyDescription:
      "Füge deinen ersten Auftrag über das Formular rechts hinzu.",
    orderDate: "Auftragsdatum",
    firstName: "Vorname",
    lastName: "Nachname",
    street: "Straße",
    additionalNotes: "Zusätzliche Hinweise",
    assignedEmployee: "Zuständiger Mitarbeiter",
    selectEmployee: "Mitarbeiter auswählen",
    completed: "Erledigt",
    transferred: "Übertragen",
    markCompleted: "Erledigt",
    markTransferred: "Übertragen",
    deleteOrder: "Löschen",
    saveClientOrder: "Auftrag hinzufügen",
    clientListTitle: "Auftragsliste",
    clientListSubtitle: "Neueste Aufträge werden hier angezeigt.",
    clientName: "Kunde",
    noNotes: "Keine zusätzlichen Hinweise",
    weeklyDescription:
      "Eine kurze Übersicht über die offene Woche. Detaillierte Berichtstabellen können später erweitert werden.",
    monthlyDescription:
      "Aktuelle Monatssummen für alle Mitarbeiter, einschließlich geschlossener Wochen.",
    settingsDescription:
      "Grundeinstellungen des Arbeitsbereichs. Hier kannst du Sprache, Logo und Passwort verwalten.",
    employeesCount: "Mitarbeiter",
    activeWeekHours: "Stunden diese Woche",
    pendingWeekPay: "Ausstehend diese Woche",
    activeMonthHours: "Stunden diesen Monat",
    pendingMonthPay: "Ausstehend diesen Monat",
    downloadMonthlyPdf: "PDF herunterladen",
  },
  pl: {
    title: "Menu panelu",
    description:
      "Wybierz sekcję, z którą chcesz teraz pracować. Pracownicy, raporty i ustawienia są rozdzielone na osobne kafelki.",
    backToMenu: "Wróć do menu",
    menu: {
      home: "Główna",
      employees: "Pracownicy",
      clients: "Kontrahenci",
      weeklyReport: "Raport tygodniowy",
      monthlyReport: "Raport miesięczny",
      settings: "Ustawienia",
      signOut: "Wyjście z panelu",
    },
    hints: {
      home: "Przegląd panelu",
      employees: "Lista i karty zespołu",
      clients: "Zamówienia i klienci",
      weeklyReport: "Godziny i wypłaty za tydzień",
      monthlyReport: "Podsumowanie bieżącego miesiąca",
      settings: "Język i opcje panelu",
      signOut: "Zakończ sesję",
    },
    weeklyTitle: "Raport tygodniowy",
    monthlyTitle: "Raport miesięczny",
    settingsTitle: "Ustawienia",
    clientsTitle: "Kontrahenci i zamówienia",
    clientsDescription:
      "Dodawaj zamówienia klientów, podawaj datę, imię i nazwisko, dodatkowe uwagi oraz pracownika odpowiedzialnego.",
    clientsEmptyTitle: "Brak zamówień",
    clientsEmptyDescription:
      "Dodaj pierwsze zamówienie z formularza po prawej stronie.",
    orderDate: "Data zamówienia",
    firstName: "Imię",
    lastName: "Nazwisko",
    street: "Ulica",
    additionalNotes: "Dodatkowe uwagi",
    assignedEmployee: "Wykonawca",
    selectEmployee: "Wybierz pracownika",
    completed: "Wykonane",
    transferred: "Przeniesione",
    markCompleted: "Wykonano",
    markTransferred: "Przenieś",
    deleteOrder: "Usuń",
    saveClientOrder: "Dodaj zamówienie",
    clientListTitle: "Lista zamówień",
    clientListSubtitle: "Najnowsze zamówienia będą widoczne tutaj.",
    clientName: "Klient",
    noNotes: "Brak dodatkowych uwag",
    weeklyDescription:
      "Krótkie podsumowanie otwartego tygodnia. Szczegółowe tabele raportów można rozbudować później.",
    monthlyDescription:
      "Bieżące miesięczne podsumowanie wszystkich pracowników z uwzględnieniem zamkniętych tygodni.",
    settingsDescription:
      "Podstawowe ustawienia panelu. Na razie dostępny jest wybór języka interfejsu.",
    employeesCount: "Pracowników",
    activeWeekHours: "Godzin w tygodniu",
    pendingWeekPay: "Do wypłaty za tydzień",
    activeMonthHours: "Godzin w miesiącu",
    pendingMonthPay: "Do wypłaty za miesiąc",
    downloadMonthlyPdf: "Pobierz PDF",
  },
} as const;

export type CabinetCopy = (typeof cabinetCopy)[LanguageCode];
